### ISSUE TITLE
date formatting broken

### ISSUE THREAD

**Issue by crowesn** [jamesvanmil/house-of-refuge#118]

**Comment by jamesvanmil** [comment]
See https://cincyrefuge.herokuapp.com/search-records/6366

**Comment by crowesn** [comment]
This may be a known issue, I'll chat with @carohansen this afternoon.

**Comment by jamesvanmil** [comment]
I had to do some weird stuff with dates to handle the leap year problems, so I may have contributed

**Comment by crowesn** [comment]
Underlying dataset has some non-compliant dates; looks like one of us opened the file in excel along the way. Carolyn is getting us a fresh export.
