### ISSUE TITLE
Image gallery, clean up and reorganize images

### ISSUE THREAD

**Issue by crowesn** [jamesvanmil/house-of-refuge#132]

**Comment by carohansen** [comment]
sorry, added the image of the little girl 2x

**Comment by carohansen** [comment]
Adding some new photos: 
![graduate](https://cloud.githubusercontent.com/assets/8903554/18761690/fd43023a-80d3-11e6-976c-f4ea0213e509.png)

![boy_with_cabinet](https://cloud.githubusercontent.com/assets/8903554/18761692/0122bb84-80d4-11e6-9af7-9fb2b3316213.png)

![cadet2](https://cloud.githubusercontent.com/assets/8903554/18761698/0567a52e-80d4-11e6-85c1-5e030f75e530.png)

**Comment by carohansen** [comment]
Spreadsheet updated with correct links: https://drive.google.com/file/d/0B-g5laJgDS4kaFM5bEtUcGFja0U/view?usp=sharing

**Comment by crowesn** [comment]
@carohansen Would you mind labeling the photos in github? The filenames didn't come through and some of them are unclear, e.g. "we honor our dead".

**Comment by carohansen** [comment]
Updated with labels.
