### ISSUE TITLE
Wireframes for image gallery

### ISSUE THREAD

**Issue by crowesn** [jamesvanmil/house-of-refuge#32]
![c7698de4-9909-11e5-9ea7-486ccce2206e](https://cloud.githubusercontent.com/assets/1069588/11598695/64fa0cea-9a91-11e5-86b6-00572caad5a1.png)
--
![cde04d7a-9909-11e5-986f-8716846dce13](https://cloud.githubusercontent.com/assets/1069588/11598696/64fddf0a-9a91-11e5-9b33-62bc23349aff.png)

**Comment by crowesn** [comment]
Can I get a wireframe for the individual image show view?

**Comment by carohansen** [comment]
![image_individual](https://cloud.githubusercontent.com/assets/8903554/11637817/ac37efac-9cf1-11e5-815f-f72708f544cb.png)

**Comment by crowesn** [comment]
Thanks!


--

Sean Crowe
Data Analyst and Developer Librarian

Digital Projects and Repositories.
University of Cincinnati Libraries
PO Box 210033
Cincinnati OH 45221-0033
Tel: (513) 556-1899
Fax: (513) 556-4393
Email: sean.crowe@uc.edu<mailto:sean.crowe@uc.edu>
gchat: crowesn





On Dec 7, 2015, at 2:49 PM, Carolyn Hansen <notifications@github.com<mailto:notifications@github.com>> wrote:


[image_individual]<https://cloud.githubusercontent.com/assets/8903554/11637817/ac37efac-9cf1-11e5-815f-f72708f544cb.png>
