### ISSUE TITLE
Wireframes for search views

### ISSUE THREAD

**Issue by crowesn** [jamesvanmil/house-of-refuge#33]
![170dc4a0-990a-11e5-87e7-d0f6b549edb6](https://cloud.githubusercontent.com/assets/1069588/11598744/b1a723a2-9a91-11e5-9ee0-486477101793.png)
--
![14474b60-990a-11e5-8bee-b1aa2ae1d1cc](https://cloud.githubusercontent.com/assets/1069588/11598746/b1adb4ec-9a91-11e5-8a45-7b02659913d1.png)
--
![118122ca-990a-11e5-98a3-701a66f67dab](https://cloud.githubusercontent.com/assets/1069588/11598745/b1ad2112-9a91-11e5-8109-e8f5c835428b.png)

**Comment by jamesvanmil** [comment]
@carohansen one more question - what would you like to happen if you *don't* select "Match all terms exactly"?
