### ISSUE TITLE
Downsample images

### ISSUE THREAD

**Issue by crowesn** [jamesvanmil/house-of-refuge#54]
Convert thumbs and other images to webscale for quicker loading.
See paperclip options for thumbs.

**Comment by crowesn** [comment]
http://www.imagemagick.org/script/convert.php

**Comment by jamesvanmil** [comment]
May not be able to install imagemagick on heroku; may need to convert and keep in the repo - let's explore.

**Comment by crowesn** [comment]
I was going to locally convert images already in the asset pipeline. We can explore for the gallery images.

**Comment by crowesn** [comment]
[related](http://stackoverflow.com/questions/3963892/heroku-running-imagemagick-w-paperclip)
