### ISSUE TITLE
Render friendly dates in admission views

### ISSUE THREAD

**Issue by crowesn** [jamesvanmil/house-of-refuge#80]

**Comment by jamesvanmil** [comment]
@carohansen what format do you like for the dates? MM/DD/YYYY or other?

**Comment by crowesn** [comment]
How important are the incorrect leap days in our data set? Ruby time will correct non-leap-year extra days in February to March 1. Is this okay?

**Comment by jamesvanmil** [comment]
We don't know what to correct them to - I think we decided to leave as is and not handle as Date objects. @carohansen amirite?

**Comment by crowesn** [comment]
So int > string and parse/reorder based on index?

**Comment by jamesvanmil** [comment]
Yup - that's what my work to-date for the field is doing. See how it's getting searched...: 

```ruby
    if params[:begin_date].blank? && params[:end_date].blank?
      # Do nothing
    elsif params[:begin_date].present? && params[:end_date].blank?
      search_params[:admission_date] = (parse_date(params[:begin_date]) - 1)..(99999999)
    elsif params[:begin_date].blank? && params[:end_date].present?
      search_params[:admission_date] = (0)..(parse_date(params[:end_date]))
    else
      search_params[:admission_date] = (parse_date(params[:begin_date]) - 1)..(parse_date(params[:end_date]))
    end
```
